const permittedObjects = [
    "Account",
    "Batch__c",
    "Batch_Assignment__c",
    "Case",
    "Contact",
    "Dealership_Assignment__c",
    "Discrepancy_LF__c",
    "Discrepancy__c",
    "Event",
    "FAQ__c",
    "Import_File__c",
    "Lead",
    "Loan__c",
    "Loan_Document__c",
    "Mailing__c",
    "Opportunity",
    "Payment__c",
    "Task",
    "Term_Assignment__c",
    "Terms__c",
    "Transaction__c",
    "Work_Assignment__c",
    "Lender__c",
    "Dealer__c",
    "Acct__c"
]

/*const omitObjects = [
    "ActivityHistory",
    "AttachedContentDocument",
    "CollaborationGroupRecord",
    "CombinedAttachment",
    "ContentDistribution",
    "ContentDocumentLink",
    "ContentVersion",
    "EmailMessage",
    "EntitySubscription",
    "EventChangeEvent",
    "EventRelation",
    "EventRelationChangeEvent",
    "FeedComment",
    "FeedItem",
    "FlowRecordRelation",
    "Loan__Feed",
    "Loan__History",
    "Loan__Share",
    "NetworkActivityAudit",
    "NetworkUserHistoryRecent",
    "Note",
    "NoteAndAttachment",
    "OpenActivity",
    "ProcessInstance",
    "ProcessInstanceHistory",
    "RecordAction",
    "Solution",

    "Group",
    "User",
    "RecordType"
]*/

module.exports = permittedObjects;