module.exports.order = [
    "Account",
    "Dealership_Assignment__c",
    "Import_File__c",
    "Terms__c",
    "Loan__c",
    "Batch__c",
    "Batch_Assignment__c",
    "Mailing__c",
    "Attachment",
    "Discrepancy_LF__c",
    "Discrepancy__c",
    "Loan_Document__c",
    "Opportunity",
    "Term_Assignment__c",
    "Payment__c",
    "Transaction__c",
    "Contact",
    "Event",
    "Task",
    "Case",
    "Lead",
    "FAQ__c"
]

module.exports.permittedObjects = [
    "Account",
    "Batch__c",
    "Batch_Assignment__c",
    "Case",
    "Contact",
    "Dealership_Assignment__c",
    "Discrepancy_LF__c",
    "Discrepancy__c",
    "Event",
    /*"FAQ__c",*/
    "Import_File__c",
    "Lead",
    "Loan__c",
    "Loan_Document__c",
    "Mailing__c",
    "Attachment",
    "Opportunity",
    "Payment__c",
    "Task",
    "Term_Assignment__c",
    "Terms__c",
    "Transaction__c",
    "Work_Assignment__c"
]

module.exports.explorableObjects = [
    "Loan__c",
    "Terms__c",
    "Term_Assignment__c",
    "Batch_Assignment__c",
    "Transaction__c",
    "Mailing__c"
]